# VillaMilaWines website docker stack
version: '3.7'

services:
  php-fpm:
    image: bitnami/php-fpm:7.1
    volumes:
      - app:/app:rw
#      - villamila_app:/app:rw
    configs:
      - source: villamila_php.ini
        target: /opt/bitnami/php-fpm/conf/php.ini
      - source: villamila_fpm.conf
        target: /opt/bitnami/php-fpm/conf/php-fpm.conf
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
#          - node.role == worker
      replicas: 1

  web:
    image: caddy:2.4.6-alpine
    volumes:
      - app:/app:ro
    networks:
      - default
      - system_dmz_network
    depends_on:
      - php-fpm
    configs:
      - source: sonata_Caddyfile
        target: /etc/caddy/Caddyfile
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
#         - node.role == worker
      replicas: 1

networks:
  default:
  system_dmz_network:
    external: true

configs:
  villamila.conf:
    external: true
  villamila_php.ini:
    external: true
  villamila_fpm.conf:
    external: true
  sonata_Caddyfile:
    external: true

volumes:
  app:
